# --- System Wide Settings ---
system: 
  # The minimum logging level (e.g., DEBUG, INFO, WARNING, ERROR).
  log_level: "INFO"
  # Time (in seconds) the application will wait for graceful shutdown before force-killing threads.
  shutdown_timeout_sec: 30

# --- Logging Settings
logging:
  # Directory where log files will be stored, auto-calculated based on OS, e.g., 
  # /var/log/ or /AppData/Local/Logs/
  log_dir: "__CALCULATE_LOG_PATH__"

  # Log file name
  log_file_name: "hallmmaos.log"

  # Max size of a single log file in bytes (10MB = 10485760)
  max_bytes: 10485760

  # Number of backup files to keep for rotation.
  backup_count: 5

# --- Task Data Repository Settings ---
tasks_data:
  # Flag: If true, the application uses local JSON/file persistence.
  # If false, it attempts to connect using the DB connection string/path.
  use_local_json: true

  # Base directory where all local data files are stored.
  # This path is calculated dynamically based on the OS.
  data_base_dir: "__CALCULATE_DATA_PATH__"

  # Filename for the active task queue data file.
  active_repo_file: "tasks_active.json"

  # Filename for the archive task data file.
  archive_repo_file: "tasks_archive.json"

  # Path to a file containing DB credentials or connection string
  # TODO: Create DB connection capabilities.

# --- LLM Settings ---
llm:
  # The LLM backend to use. Currently only supports "ollama"
  backend: "ollama"

  # The base URL where the Ollama API is running
  base_url: "http://localhost:11434"

